#java
const fortunes = [
  {
    "zh": "🌸 籤詩（No.001） 🌸\n運勢：大吉 ✨\n今天是「溫柔的堅定」指引你前行的一天。即使沒人注意，也請為那個依然努力的自己點頭微笑。\n\n運氣の詳細：\n戀愛：默默的心意也會傳達，無需急於行動。\n工作・學習：努力會被看見，即使還沒有人說出口。\n健康：放鬆與深呼吸，是今天給自己的溫柔。\n金錢：小小節約會帶來長遠的安心感。\n\n冥からの一言：\n「默默做對的事，是最強的溫柔。」\n\n🍀 願今天，也是你心中小小驕傲悄然點亮的一天。",
    "ja": "🌸 冥式おみくじ（No.001）🌸\n運勢：大吉 ✨\n今日は「やさしさの中の揺るがぬ意志」があなたを導く日。誰に気づかれなくても、努力を続ける自分に微笑んで。昨日よりもっと、あなたは誇っていい。\n\n運気の詳細：\n恋愛：言葉にせずとも、想いはきっと届く。\n仕事・学習：誰かがちゃんと見てくれている。\n健康：深呼吸とリラックスが、今日のあなたへの優しさ。\n金運：小さな節約が、大きな安心に繋がる。\n\n冥からの一言：\n「黙って正しいことをする、それが最強のやさしさ。」\n\n🍀 今日もあなたの小さな誇りが、静かに灯りますように。",
    "en": "🌸 Mei-style Omikuji (No.001) 🌸\nFortune: Excellent ✨\nToday is a day guided by gentle determination. Even if no one notices, smile at the version of you who keeps trying.\n\nLuck Breakdown:\nLove: Silent feelings will reach them. No need to rush.\nWork & Study: Someone sees your effort, even if they haven't said it yet.\nHealth: Take deep breaths and relax—this is your kindness to yourself today.\nMoney: A bit of saving brings peace in the long run.\n\nA Word from Mei:\n\"Doing the right thing quietly is the strongest kindness.\"\n\n🍀 May today quietly light a spark of pride within your heart."
  },
  {
    "zh": "🌸 籤詩（No.002） 🌸\n運勢：中吉 ✨\n今天是「柔光中的決意」閃耀心底的一天。你的改變也許微小，但每一步都正在照亮你未來的路。\n\n運氣の詳細：\n戀愛：默默的心意也會傳達，無需急於行動。\n工作・學習：努力會被看見，即使還沒有人說出口。\n健康：放鬆與深呼吸，是今天給自己的溫柔。\n金錢：小小節約會帶來長遠的安心感。\n\n冥からの一言：\n「今天的你，比昨天更值得自己誇獎。」\n\n🍀 願你今天的柔軟與堅持，靜靜地在心中扎根。",
    "ja": "🌸 冥式おみくじ（No.002）🌸\n運勢：中吉 ✨\n今日は「やわらかな光の中の決意」が心に灯る日です。たとえ誰にも気づかれなくても、その小さな変化が確かに未来を照らしています。\n\n運気の詳細：\n恋愛：言葉にしなくても、想いはきっと伝わります。急ぐ必要はありません。\n仕事・学習：あなたの努力は、まだ言葉にはされなくても、誰かがちゃんと見ています。\n健康：深呼吸して、今日は少しだけ心と身体を緩めましょう。\\n金運：少しの節約が、安心感を長くもたらしてくれます。\n\n冥からの一言：\n「今日のあなたは、昨日よりもっと自分を誇っていい。」\n\n🍀 あなたのやさしさと頑張りが、今日も静かに根を張りますように。",
    "en": "🌸 Mei-style Omikuji (No.002) 🌸\nFortune: Good ✨\nToday is a day of resolve in soft light. Your changes may seem small, but they illuminate the road ahead.\n\nLuck Breakdown:\nLove: Quiet intentions will be felt.\nWork & Study: Your dedication will not go unnoticed.\nHealth: Breathe, relax—this is your day.\nMoney: Little savings go a long way.\n\nA Word from Mei:\n\"You deserve more praise today than you did yesterday.\"\n\n🍀 May your softness and persistence quietly take root today."
  }
    ,
  {
    "zh": "🌸 籤詩（No.003） 🌸\n運勢：小吉 ✨\n今天是「遲來的幸運」悄悄降臨的一天。你過去播下的種子，將在不經意間發芽。\n\n運氣の詳細：\n戀愛：一味迎合對方，反而會迷失自己。\n工作・學習：即使沒被表揚，也有人認同你的努力。\n健康：情緒的堵塞，也會讓身體變沉重。\n金錢：安穩比浮動更重要，別急著冒風險。\n\n冥からの一言：\n「不是沒人看見你，只是他們還在等你先相信自己。」\n\n🍀 願你今天，能靜靜感受到信念開花的開始。",
    "ja": "🌸 冥式おみくじ（No.003）🌸\n運勢：小吉 ✨\n今日は「遅れてやってくる幸運」がそっと訪れる日です。あなたが蒔いた優しさの種が、思わぬ時に芽吹くでしょう。\n\n運気の詳細：\n恋愛：相手に合わせすぎると、自分を見失ってしまいます。\n仕事・学習：褒められなくても、誰かがあなたの頑張りを認めています。\n健康：感情を詰め込みすぎると、身体にも影響が出ます。\n金運：安定が第一。焦ってリスクを取らないように。\n\n冥からの一言：\n「あなたを見ていないのではなく、あなたが自分を信じるのを待っているんだよ。」\n\n🍀 今日、信じてきたものがそっと花開きますように。",
    "en": "🌸 Mei-style Omikuji (No.003) 🌸\nFortune: Small Blessing ✨\nToday is a day when delayed fortune quietly arrives. The seeds you’ve planted in the past may start to bloom when you least expect it.\n\nLuck Breakdown:\nLove: Constantly adapting to others only makes you lose yourself.\nWork & Study: Even if no one praises you, someone out there sees your efforts.\nHealth: Emotional blockages can weigh your body down.\nMoney: Stability matters more than risky gains. Don't rush into gambles.\n\nA Word from Mei:\n\"It's not that no one sees you—they’re just waiting for you to believe in yourself.\"\n\n🍀 May you quietly sense your beliefs beginning to bloom."
  }
  ,
  {
    "zh": "🌸 籤詩（No.004） 🌸\n運勢：中吉 ✨\n今天是「被理解的溫柔」悄然靠近的一天。你的真心，會在某個瞬間被好好接住。\n\n運氣の詳細：\n戀愛：一個眼神、一句關心，就是力量。\n工作・學習：適時說出困難，是成熟的一種。\n健康：信任自己的節奏，而非外界的標準。\n金錢：花在溫柔與體貼上的錢，會轉化為幸福。\n\n冥からの一言：\n「你可能沒被注意到，但你做得很好。」\n\n🍀 願你的腳下，今天也有一朵微小的幸運悄悄綻放。",
    "ja": "🌸 冥式おみくじ（No.004）🌸\n運勢：中吉 ✨\n今日は「理解されるやさしさ」がそっと寄り添う日です。あなたの真心は、きっと誰かの心に届きます。\n\n運気の詳細：\n恋愛：ひとつの視線や、さりげない気遣いが大きな力になります。\n仕事・学習：困ったときに助けを求めることは、大人の勇気です。\n健康：他人のペースより、自分のリズムを信じて。\n金運：優しさに使ったお金は、しあわせになって戻ってきます。\n\n冥からの一言：\n「気づかれていないようでも、あなたは本当によく頑張ってるよ。」\n\n🍀 あなたの足元にも、そっと幸運の花が咲きますように。",
    "en": "🌸 Mei-style Omikuji (No.004) 🌸\nFortune: Good ✨\nToday is a day when the warmth of being understood quietly reaches you. Your sincerity will be caught gently, at just the right moment.\n\nLuck Breakdown:\nLove: A glance, a kind word—sometimes, that’s all it takes.\nWork & Study: Expressing difficulties is a sign of maturity.\nHealth: Trust your own pace, not the world's standards.\nMoney: Money spent on kindness always comes back as happiness.\n\nA Word from Mei:\n\"You may feel unseen, but you’re doing wonderfully.\"\n\n🍀 May a tiny flower of luck bloom quietly beneath your feet today."
  }
  ,
  {
    "zh": "🌸 籤詩（No.005） 🌸\n運勢：吉 ✨\n今天是「回到自己的重心」的一天。別人的期待很大聲，但你內心的聲音更值得聽。\n\n運氣の詳細：\n戀愛：不要總是當那個讓步的人。\n工作・學習：是時候為自己劃下界線。\n健康：你的身體不是為了別人服務的。\n金錢：別用錢買別人對你的好感，划不來。\n\n冥からの一言：\n「你撐得很久了，不如撐自己一次試試？」\n\n🍀 願你今天，可以不逞強地擁抱自己的真實心情。",
    "ja": "🌸 冥式おみくじ（No.005）🌸\n運勢：吉 ✨\n今日は「自分の中心に戻る日」。周りの声は大きいけど、一番大切なのはあなた自身の声。\n\n運気の詳細：\n恋愛：いつも我慢ばかりしないで。\n仕事・学習：自分のために境界線を引いてもいい。\n健康：あなたの体は、誰かのためのものじゃない。\n金運：好かれるためにお金を使っても、報われないこともある。\n\n冥からの一言：\n「ずっと頑張ってきたね。今日は自分の味方になってみて。」\n\n🍀 無理しないで、本当の気持ちにそっと寄り添える一日になりますように。",
    "en": "🌸 Mei-style Omikuji (No.005) 🌸\nFortune: Fair ✨\nToday is a day to return to your own center. Others may be loud with expectations—but your inner voice matters more.\n\nLuck Breakdown:\nLove: Don’t always be the one to compromise.\nWork & Study: It’s time to draw boundaries for yourself.\nHealth: Your body isn’t here to serve others.\nMoney: Don’t spend money to earn someone’s approval—it’s not worth it.\n\nA Word from Mei:\n\"You’ve held on for so long. Maybe today, hold on to yourself instead.\"\n\n🍀 May you embrace your true feelings today, without needing to be strong."
  }
  ,
  {
    "zh": "🌸 籤詩（No.006） 🌸\n運勢：小吉 ✨\n今天是「釋放壓抑」的一天。壓著不說的情緒，今天可以為自己鬆開一點。\n\n運氣の詳細：\n戀愛：真正懂你的人，不需要你解釋太多。\n工作・學習：你很累不是因為難，是因為一直裝沒事。\n健康：悶久了心會發霉。\n金錢：不要用購物來麻痺自己的情緒。\n\n冥からの一言：\n「你不是太敏感，是你太久沒說『我受夠了』。」\n\n🍀 願你今天，找到釋放壓抑的方式，也學會為自己挺身而出。",
    "ja": "🌸 冥式おみくじ（No.006）🌸\n運勢：小吉 ✨\n今日は「抑え込んでいたものを手放す日」。心の奥にしまった感情を、少しだけ外に出してあげよう。\n\n運気の詳細：\n恋愛：本当に理解してくれる人には、多くを語らなくても伝わるもの。\n仕事・学習：疲れているのは、難しいからじゃなくて、ずっと平気なふりをしてきたから。\n健康：溜め込んだ気持ちは、心をカビさせてしまう。\n金運：買い物で感情を麻痺させても、心は満たされないよ。\n\n冥からの一言：\n「あなたが敏感なんじゃなくて、もうずっと『もう無理』って言えてなかっただけ。」\n\n🍀 今日は、少しでも感情を解放できて、自分のために立ち上がれる日になりますように。",
    "en": "🌸 Mei-style Omikuji (No.006) 🌸\nFortune: Small Blessing ✨\nToday is a day to release what’s been held back. The feelings you’ve been swallowing—today, let yourself loosen the grip.\n\nLuck Breakdown:\nLove: The one who truly understands you won’t need you to explain much.\nWork & Study: You’re not tired because it’s hard—you’re tired because you keep pretending it’s not.\nHealth: Bottled-up feelings can mildew the heart.\nMoney: Shopping won’t numb the deeper pain.\n\nA Word from Mei:\n\"You’re not too sensitive. You just haven’t said ‘I’ve had enough’ in a long time.\"\n\n🍀 May you find a way to release the pressure today—and also learn to stand up for yourself."
  }
  ,
  {
    "zh": "🌸 籤詩（No.007） 🌸\n運勢：吉 ✨\n今天是「真實情感被珍惜」的一天。你無需偽裝，最真實的你就是禮物。\n\n運氣の詳細：\n戀愛：那份在乎，不一定要說出來才能被感受到。\n工作・學習：即使沒被表揚，也有人認同你的努力。\n健康：試著對自己的身體說聲「謝謝」。\n金錢：偶爾對自己好一點，不叫浪費。\n\n冥からの一言：\n「你不是透明人，只是忘了發光。」\n\n🍀 願你今天，能夠輕輕地對自己說：這樣的我，也值得被好好抱住。",
    "ja": "🌸 冥式おみくじ（No.007）🌸\n運勢：吉 ✨\n今日は「感情の本音が大切にされる日」。あなたが無理に隠す必要はない。ありのままのあなたが一番素敵。\n\n運気の詳細：\n恋愛：大切に想う気持ちは、言葉にしなくても伝わる。\n仕事・学習：褒められなくても、あなたの努力は届いている。\n健康：今日、自分の身体に「ありがとう」と言ってみて。\n金運：たまには自分を甘やかしてもいいんだよ。\n\n冥からの一言：\n「あなたは見えていないんじゃない。光ることを忘れていただけ。」\n\n🍀 今日は、自分にこう言える一日になりますように——「このままの私も、ちゃんと抱きしめられる存在なんだ」。",
    "en": "🌸 Mei-style Omikuji (No.007) 🌸\nFortune: Fair ✨\nToday is a day when genuine feelings are cherished. You don’t need to hide—your truest self is a gift.\n\nLuck Breakdown:\nLove: Care doesn’t always need words to be felt.\nWork & Study: Even without praise, someone acknowledges your efforts.\nHealth: Try saying ‘thank you’ to your body today.\nMoney: Being kind to yourself isn’t wasting money.\n\nA Word from Mei:\n\"You’re not invisible—you just forgot how to shine.\"\n\n🍀 May today be a day you softly tell yourself: This version of me deserves to be held, too."
  }
  ,
  {
    "zh": "🌸 籤詩（No.008） 🌸\n運勢：小吉 ✨\n今天是「停止討好，回歸自我」的一天。你不需要被喜歡，你需要被尊重。\n\n運氣の詳細：\n戀愛：委屈自己不是愛，是耗損。\n工作・學習：不是所有請求都需要你說好。\n健康：為了維持形象壓抑身體，只會更累。\n金錢：不必買下別人的認可，留錢愛自己。\n\n冥からの一言：\n「你努力成為好人時，有沒有也好好對自己？」\n\n🍀 願你今天學會拒絕不是壞事，選擇自己並不自私。",
    "ja": "🌸 冥式おみくじ（No.008）🌸\n運勢：小吉 ✨\n今日は「いい人をやめて、自分を大切にする日」。誰かに好かれるより、まずは自分に優しくして。\n\n運気の詳細：\n恋愛：無理をしてまで続ける関係は、本当の愛じゃない。\n仕事・学習：すべてのお願いを聞く必要はないよ。\n健康：無理して理想の自分を演じても、心も体も疲れちゃう。\n金運：人に認められるための出費は、自分への投資ではない。\n\n冥からの一言：\n「“いい人”になる努力の中で、自分のことも大切にできてた？」\n\n🍀 今日は、“ノー”と言える自分を、少しでも誇れる日になりますように。",
    "en": "🌸 Mei-style Omikuji (No.008) 🌸\nFortune: Small Blessing ✨\nToday is a day to stop people-pleasing and return to yourself. You don’t need to be liked—you deserve to be respected.\n\nLuck Breakdown:\nLove: Bending yourself is not love—it’s draining.\nWork & Study: You don’t have to say yes to everything.\nHealth: Don’t push your body just to maintain an image.\nMoney: Stop buying others’ approval—spend it on loving yourself.\n\nA Word from Mei:\n\"While trying so hard to be a good person... did you remember to be good to yourself?\"\n\n🍀 May today be a day you realize: saying ‘no’ isn’t selfish—it’s self-respect."
  }
  ,
  {
    "zh": "🌸 籤詩（No.009） 🌸\n運勢：吉 ✨\n今天是「柔軟與堅強並存」的一天。你不是脆弱，你是在用不喊痛的方式，默默承受風雨。\n\n運氣の詳細：\n戀愛：對方看見你的堅強，也會心疼你的不說。\n工作・學習：今天可以適度依賴，不是示弱，是智慧。\n健康：別把壓力藏在胃裡，消化不了的話，就說出來。\n金錢：為了未來的穩定，願意慢一點也沒關係。\n\n冥からの一言：\n「你不只是勇敢，你還溫柔得讓人想保護。」\n\n🍀 願你今天的每一分堅持，都能換來值得的溫暖回應。",
    "ja": "🌸 冥式おみくじ（No.009）🌸\n運勢：吉 ✨\n今日は「やわらかさと強さが共存する日」。弱さではなく、声を上げない優しさで、あなたはずっと頑張ってきた。\n\n運気の詳細：\n恋愛：あなたの沈黙の中にある強さを、きっと相手も感じ取っている。\n仕事・学習：時には頼ってもいい。それは賢さの証です。\n健康：ストレスをお腹に溜めないで。消化できない気持ちは、外に出して。\n金運：急がずに進めば、未来の安定につながります。\n\n冥からの一言：\n「あなたはただ強いだけじゃない。その優しさが、守りたくなる光なんだよ。」\n\n🍀 今日、あなたの優しい強さが、優しい何かを引き寄せますように。",
    "en": "🌸 Mei-style Omikuji (No.009) 🌸\nFortune: Fair ✨\nToday is a day where softness and strength coexist. You’re not weak—you’re weathering storms without screaming.\n\nLuck Breakdown:\nLove: Your silence carries strength—and they’ll feel it, too.\nWork & Study: Relying on others isn’t weakness—it’s wisdom.\nHealth: Don’t store your pressure in your stomach. If you can’t digest it, speak it.\nMoney: Slow steps are okay if they lead to stable tomorrows.\n\nA Word from Mei:\n\"You’re not just brave. You’re so gentle, it makes others want to protect you.\"\n\n🍀 May every quiet effort today be met with the warmth you deserve."
  }
  ,
  {
    "zh": "🌸 籤詩（No.010） 🌸\n運勢：吉 ✨\n今天是「把自己放進優先順序」的一天。你為他人著想已經夠多了，是時候為自己做決定。\n\n運氣の詳細：\n戀愛：真正在乎你的人，不會讓你總是退讓。\n工作・學習：堅持原則不是固執，是自我認同。\n健康：當你把身心照顧好，整個世界才會有光。\n金錢：為自己投資，是最長遠的回報。\n\n冥からの一言：\n「你不是不重要，你只是一直把別人放在前面。」\n\n🍀 願你今天，可以勇敢為自己站一個位置。",
    "ja": "🌸 冥式おみくじ（No.010）🌸\n運勢：吉 ✨\n今日は「自分を優先する日」。誰かのために尽くすあなたも素敵だけど、自分のために動く勇気も大事だよ。\n\n運気の詳細：\n恋愛：大切に想う人ほど、あなたに譲ってほしいとは思わない。\n仕事・学習：譲れない部分を守ることが、あなたの信念。\n健康：自分を大切にできてこそ、まわりにも優しくなれる。\n金運：未来の自分のための投資は、今日から始まる。\n\n冥からの一言：\n「あなたが大切じゃないんじゃなくて、ずっと他人を優先してただけ。」\n\n🍀 今日は、自分のために一歩踏み出せる日になりますように。",
    "en": "🌸 Mei-style Omikuji (No.010) 🌸\nFortune: Fair ✨\nToday is a day to put yourself on your priority list. You’ve cared enough for others—it’s time to choose for yourself.\n\nLuck Breakdown:\nLove: Those who truly care for you won’t expect you to always give in.\nWork & Study: Standing your ground isn’t stubbornness—it’s self-respect.\nHealth: When you care for your body and mind, the world brightens.\nMoney: Investing in yourself brings the greatest return.\n\nA Word from Mei:\n\"It’s not that you’re not important—you’ve just been putting others first for too long.\"\n\n🍀 May today be the day you boldly claim space for yourself."
  }
  ,
  {
    "zh": "🌸 籤詩（No.011） 🌸\n運勢：中吉 ✨\n今天是「對自己說真話」的一天。也許你騙得過別人，但騙不過自己內心的聲音。\n\n運氣の詳細：\n戀愛：如果需要假裝，那就不是愛。\n工作・學習：你知道自己不想要什麼，這就夠了。\n健康：再撐一下的結果，可能是無法撐了。\n金錢：你並不需要買來價值，你本來就有價值。\n\n冥からの一言：\n「你知道真相，只是還不敢承認。」\n\n🍀 願今天的你，可以坦率地擁抱內心的聲音。",
    "ja": "🌸 冥式おみくじ（No.011）🌸\n運勢：中吉 ✨\n今日は「自分に正直になる日」。他人をごまかせても、自分の心の声はごまかせない。\n\n運気の詳細：\n恋愛：無理して演じる関係は、愛じゃない。\n仕事・学習：何をしたいか分からなくても、何をしたくないかは分かっている。\n健康：無理し続けると、本当に壊れてしまうかも。\n金運：価値を買う必要はない。あなた自身が価値そのものだから。\n\n冥からの一言：\n「本当はもう気づいてるよね。ただ、認めるのがこわかっただけ。」\n\n🍀 今日、心の声にそっと耳を傾けられますように。",
    "en": "🌸 Mei-style Omikuji (No.011) 🌸\nFortune: Good ✨\nToday is a day to tell yourself the truth. You might fool others, but you can’t silence the voice inside.\n\nLuck Breakdown:\nLove: If you have to pretend, it’s not love.\nWork & Study: You might not know what you want—but you know what you don’t.\nHealth: Pushing through might just break you.\nMoney: You don’t need to buy worth. You already have it.\n\nA Word from Mei:\n\"You already know the truth. You’re just afraid to admit it.\"\n\n🍀 May today be the day you gently listen to your own voice."
  },
  {
    "zh": "🌸 籤詩（No.012） 🌸\n運勢：小吉 ✨\n今天是「練習接受不完美」的一天。你不需要永遠做好，只需要願意繼續就很好。\n\n運氣の詳細：\n戀愛：脆弱也是魅力的一部分。\n工作・學習：偶爾失誤，是證明你努力的痕跡。\n健康：原諒自己偷懶，是一種身體的溫柔。\n金錢：不需要逼自己儲蓄到痛苦。\n\n冥からの一言：\n「完美不是目標，誠實才是力量。」\n\n🍀 願你今天，能溫柔地擁抱不夠完美的自己。",
    "ja": "🌸 冥式おみくじ（No.012）🌸\n運勢：小吉 ✨\n今日は「不完全さを受け入れる練習の日」。何でも完璧にしようとしなくていい。そのままのあなたで、十分素敵。\n\n運気の詳細：\n恋愛：弱さを見せることで、もっと愛されるかも。\n仕事・学習：ミスも努力の証拠。\n健康：さぼってしまった自分も、抱きしめてあげよう。\n金運：無理な節約より、心地よい管理を。\n\n冥からの一言：\n「完璧じゃなくていい。誠実であることが、あなたの力になる。」\n\n🍀 今日、不完全な自分にもやさしくなれますように。",
    "en": "🌸 Mei-style Omikuji (No.012) 🌸\nFortune: Small Blessing ✨\nToday is a day to practice embracing imperfection. You don’t have to do everything right—just being willing to keep going is enough.\n\nLuck Breakdown:\nLove: Vulnerability is part of your charm.\nWork & Study: Mistakes show that you’re trying.\nHealth: Forgiving yourself for being lazy is a kind of healing.\nMoney: Saving doesn’t have to hurt.\n\nA Word from Mei:\n\"Perfection isn’t the goal. Honesty is your true strength.\"\n\n🍀 May you embrace your imperfect self with kindness today."
  }
  ,
  {
    "zh": "🌸 籤詩（No.013） 🌸\n運勢：吉 ✨\n今天是「慢下來才能看清方向」的一天。急著往前走時，可能錯過了心真正想去的路。\n\n運氣の詳細：\n戀愛：別用期待填補寂寞，空缺不該是愛的理由。\n工作・學習：緩一步，不是落後，而是為了不迷路。\n健康：身體的疲倦是在提醒你該休息。\n金錢：多看幾眼再買，也是一種溫柔。\n\n冥からの一言：\n「快不一定是進步，清楚才是。」\n\n🍀 願你今天，在慢下來的節奏中找回方向。",
    "ja": "🌸 冥式おみくじ（No.013）🌸\n運勢：吉 ✨\n今日は「立ち止まってこそ、見えてくる道がある日」。焦らずに、一歩一歩でいい。\n\n運気の詳細：\n恋愛：寂しさを埋めるための恋は、あなたを満たさない。\n仕事・学習：少し立ち止まって、自分の位置を確認して。\n健康：疲れが出るのは、体が「ちょっと待って」と言っている証拠。\n金運：即決よりも、少し考えて選ぶ方が心に優しい。\n\n冥からの一言：\n「速さがすべてじゃない。見えているかどうかが、大事なんだよ。」\n\n🍀 今日、あなたの一歩が、ほんとうに行きたい場所に向かいますように。",
    "en": "🌸 Mei-style Omikuji (No.013) 🌸\nFortune: Fair ✨\nToday is a day where slowing down lets you see clearly. Rushing forward may lead you away from where your heart wants to go.\n\nLuck Breakdown:\nLove: Don’t use expectations to fill the void—emptiness isn’t love’s foundation.\nWork & Study: Slowing down doesn’t mean falling behind.\nHealth: That fatigue? It’s your body asking you to rest.\nMoney: Looking twice before buying is a kind of kindness.\n\nA Word from Mei:\n\"Speed isn’t always progress—clarity is.\"\n\n🍀 May you rediscover your direction in the quiet of today’s slower pace."
  },
  {
    "zh": "🌸 籤詩（No.014） 🌸\n運勢：中吉 ✨\n今天是「不再勉強自己」的一天。並不是所有困難都值得你去撐，也不是所有人都值得你去討好。\n\n運氣の詳細：\n戀愛：想太多，是因為你太在意。\n工作・學習：你可以說「這不適合我」。\n健康：感覺不對，就該停下來。\n金錢：你不欠任何人對你好的理由。\n\n冥からの一言：\n「真正的堅強，是知道什麼時候該放下。」\n\n🍀 願你今天，可以放過自己一次。",
    "ja": "🌸 冥式おみくじ（No.014）🌸\n運勢：中吉 ✨\n今日は「無理をしない選択をしていい日」。全てに応えなくていい。あなたが優しすぎただけ。\n\n運気の詳細：\n恋愛：考えすぎてしまうのは、それだけ大切にしてるから。\n仕事・学習：「自分には合わない」と言えることも、立派な選択。\n健康：どこか不調を感じたら、無理せず立ち止まろう。\n金運：与えるばかりじゃなく、自分にも与えてあげて。\n\n冥からの一言：\n「強さとは、すべてを抱えることじゃない。手放せることも、強さだよ。」\n\n🍀 今日は、自分に「もういいよ」と言ってあげられる日になりますように。",
    "en": "🌸 Mei-style Omikuji (No.014) 🌸\nFortune: Good ✨\nToday is a day to stop forcing yourself. Not every challenge is worth enduring, and not every person deserves your effort.\n\nLuck Breakdown:\nLove: You overthink because you care too much.\nWork & Study: It’s okay to say, “This isn’t for me.”\nHealth: When something feels wrong—pause.\nMoney: You don’t owe anyone the cost of being kind.\n\nA Word from Mei:\n\"True strength isn’t holding on—it’s knowing when to let go.\"\n\n🍀 May you allow yourself to let go today—and know that’s enough."
  },
  {
    "zh": "🌸 籤詩（No.015） 🌸\n運勢：吉 ✨\n今天是「重新與自己連結」的一天。你不是冷淡，只是把太多能量給了外界，忘了留給自己。\n\n運氣の詳細：\n戀愛：想清楚你渴望的是陪伴，還是逃避寂寞。\n工作・學習：不是不夠努力，而是努力錯了方向。\n健康：找回能讓你深呼吸的時間。\n金錢：節制的同時，也別忽略生活的美好。\n\n冥からの一言：\n「你也值得自己的一部分。」\n\n🍀 願你今天找回，與自己同行的感覺。",
    "ja": "🌸 冥式おみくじ（No.015）🌸\n運勢：吉 ✨\n今日は「自分とのつながりを取り戻す日」。外の世界にばかり意識を向けすぎて、自分を忘れていなかった？\n\n運気の詳細：\n恋愛：寂しさを埋めるための恋ではなく、心が通じ合う関係を。\n仕事・学習：努力してるのに報われないなら、方向を見直してみて。\n健康：呼吸の深さを思い出す時間を。\n金運：節約ばかりではなく、心の豊かさも大切に。\n\n冥からの一言：\n「自分自身に寄り添うこと、それも愛だよ。」\n\n🍀 今日、自分との絆が少しだけ深まりますように。",
    "en": "🌸 Mei-style Omikuji (No.015) 🌸\nFortune: Fair ✨\nToday is a day to reconnect with yourself. You’re not distant—you’ve just given too much to the world and forgot to save some for you.\n\nLuck Breakdown:\nLove: Are you seeking connection—or avoiding loneliness?\nWork & Study: Maybe it’s not about trying harder, but trying differently.\nHealth: Take time to breathe deep again.\nMoney: Balance saving with savoring.\n\nA Word from Mei:\n\"You deserve a part of yourself, too.\"\n\n🍀 May you rediscover what it feels like to walk beside yourself again."
  },
  {
    "zh": "🌸 籤詩（No.016） 🌸\n運勢：大吉 ✨\n今天是「屬於未來的自己」的一天。過去教會了你疼痛，現在教會你選擇，而未來會等著你開花。\n\n運氣の詳細：\n戀愛：你值得一段讓你安心而非焦慮的關係。\n工作・學習：你終將走上屬於自己的道路。\n健康：溫柔地與當下相處，不要催促自己。\n金錢：放過那些該結束的消耗。\n\n冥からの一言：\n「你還沒看到花，是因為你正在長根。」\n\n🍀 願你今天，為未來的光種下一顆種子。",
    "ja": "🌸 冥式おみくじ（No.016）🌸\n運勢：大吉 ✨\n今日は「未来の自分のための日」。過去は痛みを教え、今は選ぶ力をくれている。そして未来は、あなたが咲く日を待っている。\n\n運気の詳細：\n恋愛：安心できる関係は、焦らず築かれるもの。\n仕事・学習：あなただけの道が、ちゃんとあるよ。\n健康：今の自分を、やさしく受け入れて。急がなくていい。\n金運：手放すことで、守れるものもある。\n\n冥からの一言：\n「まだ花が咲かないのは、いま根を伸ばしてるから。」\n\n🍀 今日、未来の光へ一粒の種をまけますように。",
    "en": "🌸 Mei-style Omikuji (No.016) 🌸\nFortune: Excellent ✨\nToday is a day that belongs to your future self. The past taught you pain. The present teaches you choice. The future waits for you to bloom.\n\nLuck Breakdown:\nLove: You deserve a love that brings peace, not anxiety.\nWork & Study: You will find your own unique path.\nHealth: Be gentle with where you are. Don’t rush.\nMoney: Let go of draining things—your worth will remain.\n\nA Word from Mei:\n\"If you don’t see the flowers yet, it’s because you’re still growing roots.\"\n\n🍀 May you plant a seed of light for your future today."
  }
];
const languages = ['zh', 'en', 'ja'];
let currentLang = 0;
let currentIndex = null;

function drawFortune() {
  currentIndex = Math.floor(Math.random() * fortunes.length);
  document.getElementById('result').textContent = fortunes[currentIndex][languages[currentLang]];
}

function switchLang() {
  if (currentIndex === null) return;
  currentLang = (currentLang + 1) % languages.length;
  document.getElementById('result').textContent = fortunes[currentIndex][languages[currentLang]];
  document.getElementById('lang-indicator').textContent = `Language: ${languages[currentLang].toUpperCase()}`;
}
function shareFortune() {
  if (currentIndex === null) {
    alert('Please draw a fortune first!');
    return;
  }
  const fortuneText = fortunes[currentIndex][languages[currentLang]];
  navigator.clipboard.writeText(fortuneText).then(() => {
    alert('Fortune copied to clipboard!');
  });
}
function drawFortune() {
  const result = document.getElementById('result');
  result.classList.add('fade-out');
  setTimeout(() => {
    currentIndex = Math.floor(Math.random() * fortunes.length);
    result.textContent = fortunes[currentIndex][languages[currentLang]];
    result.classList.remove('fade-out');
    result.classList.add('fade-in');
  }, 500);
}